spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/capstone?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver